### ISSUE TITLE
Why `wget --no-check-certificate https://raw.github.com/…`?

### ISSUE THREAD

**Issue by ypid** [volkszaehler/volkszaehler.org#601]
Just noticed this in the wiki and fixed/removed the `--no-check-certificate` because this *should not* be needed. It is also mentioned in the [README](https://github.com/volkszaehler/volkszaehler.org#quickstart). Can it be updated there as well or did I miss something?

**Comment by r00t-** [comment]
most likely because at the time it was written the CA github is/was using was not installed on the author's system or generally not widely pre-installed.
it often happens that ca-certs installed on systems are lagging behind (more than in browsers). been there.

ofcourse it's security-wise a bad idea to instruct users to ignore the cert, especially when executing code straight off the remote server.
it should be removed.
